### ISSUE TITLE
Use with SQLite?

### ISSUE THREAD

**Issue by brody2consult** [terkelg/sqliterally#6]
I recently found this while looking at a couple of other packages by @terkelg, was wondering if anyone had experience making this work with SQLite libraries such as node-sqlite3 or SQL.js.

I maintain a widely used SQLite plugin component for Apache Cordova, hope to take a closer look at this in the near future.

**Comment by terkelg** [comment]
It's pretty generic – I think it should be possible aIt should be possible to use with other libraries. Let me know how it goes. I'm open to do minor tweaks if needed be

**Comment by brody2consult** [comment]
That's what I figured, thanks. I hope to try it soon, unfortunately dealing with some other priorities at the moment.
